# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-14 20:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='abstract',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='last_modified',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='New Document', max_length=120),
        ),
    ]
