# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-14 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20161214_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Final'), (2, 'Final revizuit'), (3, 'Blocat')], default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.FloatField(default=0.1),
        ),
    ]
