# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-14 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20161214_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
