# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
