# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
