# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20161215_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stale',
            field=models.BooleanField(default=False),
        ),
    ]
