# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-15 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_stale'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stale_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
