# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-22 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0010_auto_20170119_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='requires_signature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
