# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-19 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0010_auto_20170119_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxinstance',
            name='accepted_by',
        ),
        migrations.AddField(
            model_name='fluxinstance',
            name='accepted_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='accepted_flux', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='fluxinstance',
            name='steps',
        ),
        migrations.AddField(
            model_name='fluxinstance',
            name='steps',
            field=models.ManyToManyField(blank=True, default=None, related_name='in_instance_fluxes', to='documents.Step'),
        ),
        migrations.RemoveField(
            model_name='fluxmodel',
            name='acceptance_criteria',
        ),
        migrations.AddField(
            model_name='fluxmodel',
            name='acceptance_criteria',
            field=models.ManyToManyField(blank=True, null=True, related_name='flux_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='fluxmodel',
            name='groups',
        ),
        migrations.AddField(
            model_name='fluxmodel',
            name='groups',
            field=models.ManyToManyField(related_name='visible_flux', to='auth.Group'),
        ),
        migrations.RemoveField(
            model_name='fluxmodel',
            name='steps',
        ),
        migrations.AddField(
            model_name='fluxmodel',
            name='steps',
            field=models.ManyToManyField(related_name='in_model_fluxes', to='documents.Step'),
        ),
        migrations.AlterField(
            model_name='step',
            name='document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_step_fluxes', to='documents.Document'),
        ),
    ]
