# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.IntegerField(choices=[(1, 'Cititor'), (2, 'Contributor'), (3, 'Manager')], default=1)),
            ],
        ),
    ]
