# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Cititor'), (2, 'Contribuitor'), (3, 'Manager'), (4, 'Administrator')], default=1),
        ),
    ]
