# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='templateuri/%Y/%m/%d/')),
                ('filename', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('fields', models.CharField(max_length=2500)),
                ('filetype', models.CharField(max_length=100)),
            ],
        ),
    ]
