# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-21 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateuri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='fields',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='filetype',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
